name: Publish to GitHub Pages

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: npm install && npm run build

